---
layout: post
title: "Review: No Other Choice (2025)"
date: 2026-04-12
categories: film
tags: [Film, No Other Choice, Park Chan-Wook, Old Boy]
---

*No Other Choice* was disappointing considering Park Chan-wook's previous films, though the mise-en-scène was impressive.

What I expect from Park's films, as an audience, is the intimacy between his figures. His films carry a distinctly Japanese quality in mood and sensibility—by "Japanese," I mean the peculiar darkish backgrounds and cold mise-en-scène that enable a kind of violence all the more brutal for its detachment. Unlike the Korean sentiment of "you don't have to push it to the end," Park drives his conflicts forward until they exhaust themselves, sometimes spilling into settings that feel beyond the reach of ordinary reality. I believe his aesthetic achievement lies in the fact that he has always understood something the Japanese style alone cannot provide: the entanglement of relationships between his characters. His films carry something distinctly Korean in the way love and obsession operate—in *JSA*, a comradeship between South and North Korean soldiers that edges toward something more than brotherhood; in *The Handmaiden*, that same undercurrent made explicit; in the Vengeance trilogy, figures who endure and suffer until they finally reach the moment of revenge; and in *Decision to Leave*, the palpable tension between professional duty and personal feeling. 

This film has less of that.

It is good enough to be one of any festival-nominated works—I want to be clear about that. But the intimacy Park has shown us before is here reduced to an object: the house. Emotion between characters is too restrained. In other words, the narrative element that once elevated his cold, Japanese-inflected mise-en-scène into something humanly irreducible is no longer conspicuous here. Park’s previous films visualize brutality while condensing the figures’ desperate tragedy, obsession, and tension so that the moment of emotional release occurs dramatically, much like in a melodrama. In *Oldboy* and *Lady Vengeance*, the drive for revenge dominates the narrative from beginning to end, pulling the story toward its peak. The figures obsessed by revenge are depicted as cold and emotionally hollow, set in contrast against the emotional turmoil expressed by those on whom they seek revenge. In *Oldboy*, Lee Woo-jin, who imprisons Oh Dae-su in an unreal, prison-like space and is depicted almost as a sociopath who treats people as toys, finally unleashes decades of accumulated feeling in the moment before he chooses his death. In *Lady Vengeance*, the coldly spoken “Mind your own business” gives way as the film nears its end to Geum-ja’s reunion with her daughter, who had been held hostage—and though the narration says that she cannot seek salvation after completing her revenge, as she relearns human emotion through those around her, the screen that had turned black and white finds its color again. 

*No Other Choice* carries the opposite narrative structure from Park’s revenge films. Man-su starts as someone emotionally attached to his family and home and gradually loses his capacity for empathy. For his first murder, he takes time to research his target—observing what kind of person they are and how their family is falling apart. When the moment arrives, he tears off the layers of cloth clumsily wrapped around the gun—reminiscent of Lee Byung-hun hastily assembling a firearm in Kim Jee-woon’s *A Bittersweet Life*—and kills in an explosion of emotion. But the subsequent killings occur with less emotion, almost too smoothly to sustain tension, and his attempt to cover up his son’s misconduct by threatening in the middle of the sequence reveals how much has changed inside him. Having secured the job he wanted through a series of murders, Man-su walks through an empty factory, and the audience can confirm that his human connection has disappeared. He manages to hold onto the house and family he was so attached to—but the view of his home from outside at the end confirms that warmth no longer lives there.

The Vengeance trilogy and *No Other Choice* both share a characteristic: figures positioned at the periphery of the central events appear in both. These figures introduce change into the protagonist’s emotional world and offer a way out of the cycle of violence. In *Oldboy*, Mido is Oh Dae-su’s daughter, a figure who offers salvation from his suffering and guilt. The snowy mountain where Oh Dae-su sees Mido feels like a space removed from reality—and it is there that Park suggests these two will carry the weight of what Lee Woo-jin set, reuniting outside the world that destroyed them. 

In *No Other Choice*, Park appears to have intended this role for Man-su’s daughter. She appears throughout as someone apart from the normal order—she studies cello but never plays for her family—until the final scene, where those around her quietly witness her playing. At a post-screening gathering at the Korean Cultural Center New York in December 2025, a friend of mine asked Park directly how to read the scene, and Park answered that the daughter exists on a different level from Man-su’s deteriorating world, a figure still capable of communicating with nature. So, ironically, where the figures in the Vengeance trilogy opened a passage back toward reality for their broken protagonists, the daughter in *No Other Choice* delivers a warning and points toward an inevitable ruin.

This is where we need to ask what exactly the warning is and what has gone wrong. Many film reviews viewed it as a critique of contemporary capitalism—of a society that discards people the moment they are no longer needed, of a world after AI in which human labor becomes obsolete. That reading holds, yet a critique of capitalism alone cannot account for what makes Park’s film distinct.

For someone who has followed Park’s films closely, watching the film as a capitalist dark fairy tale leaves something unresolved. Park’s previous films worked through a structure where figures trapped inside violent systems infected one another with their emotions—and, in doing so, found something like salvation. In *JSA*, soldiers on opposite sides of an ideological divide share what cannot otherwise be spoken. In *Oldboy*, the two main characters, Mido and Oh Dae-su, share grief and guilt. Whether one reads the endings as tragic or not is, in a sense, beside the point—what mattered was that the entangled relationships existed within the same tragedy so that cruelty and humanism were never separable and always bound together. 

In *No Other Choice*, that role falls to the daughter—but she appears not as someone who entangles with Man-su or offers him salvation but as a figure separated from him. Park’s violence has always existed as a device to maximize emotional entanglement between figures—and without that entanglement, the explosive emotional release that once defined his work simply does not arrive. 

*No Other Choice* loses its complexity because its emotional release stays unresolved. The contrast between Man-su and his daughter is too clear—a father losing his humanity set against a daughter still capable of communication with nature. The film's message is clarified, but it fixes Man-su as a morally simple figure. The reason he chose this path is entirely explained by “the logic of capitalism,” and the daughter, standing outside that logic as a figure of pure contrast, appears as a one-dimensional character. Where Park’s earlier films showcased us figures who were neither victims nor perpetrators in any sense—whose moral complexity drove the narrative forward—this film moves as though its violence were a series of predetermined steps. The brutality feels weightless at times, and the audience watches Man-su from a distance—never implicated, never inside it.

Park has said he first thought of adapting a scenario based on Donald Westlake’s novel *The Ax* over twenty years ago, around the time he was making the Vengeance trilogy. That proximity makes a structural comparison between this film and his early work feel natural. Given that Park depicts a figure whose humanity structural forces gradually destroy, he may have chosen to focus Man-su’s obsession on the house rather than on other people, maintaining emotional distance to deliver a clearer message. But as Man-su grows more brutal and the audience grows more distant from him, the figure’s single-minded trajectory can only gesture toward the contradiction of the social structure rather than embody it. The audience ends up confirming a predicted consequence—and that, paradoxically, weakens the film’s social criticism. 
 
